/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * CargaHdr.java
 *
 * Created on 04-abr-2012, 8:32:31
 */
package Reparto.pantallas;

import java.sql.SQLException;
import java.text.DecimalFormat;
import java.util.ArrayList;
import java.util.Iterator;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import Reparto.DetalleHdr;
import Reparto.EncabezadoHdr;
import Reparto.GuardarRecepcionHdr;
import Reparto.ModificacionesHdr;
import Reparto.PedidosParaReparto;
import Reparto.interfaces.AbmHdr;
import Reparto.interfaces.Procesos;
import tablas.MiModeloTablaCargaHdr;

/**
 *
 * @author Administrador
 */
public class CargaHdr extends javax.swing.JInternalFrame {

    /** Creates new form CargaHdr */
    static ArrayList detalleHdr=new ArrayList();
    static EncabezadoHdr hdr=new EncabezadoHdr();
    static ArrayList encabezados=new ArrayList();
    static int cantidad=0;
    static int limiteSuperior=0;
    static int limiteInferior=1;
    static String fechaReparto;
    
    public CargaHdr() {
        initComponents();
        try {
            cargarHdr();
        } catch (SQLException ex) {
            Logger.getLogger(CargaHdr.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        jPanel4 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jTextField9 = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jTextField10 = new javax.swing.JTextField();
        jTextField11 = new javax.swing.JTextField();
        jTextField12 = new javax.swing.JTextField();
        jTextField13 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        MiModeloTablaCargaHdr crg=new MiModeloTablaCargaHdr();
        AbmHdr pr=new DetalleHdr();
        DetalleHdr detalle=new DetalleHdr();
        Boolean ent=true;
        System.out.println(" hdr "+cantidad);
        try{
            detalleHdr=pr.cargarItemsHdr(cantidad);
        }catch(Exception ex){
            System.out.println(" NO SE CARGO EL DETALLE DE HDR "+ex);
        }
        jTable1 = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jPanel3 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextField3 = new javax.swing.JTextField();
        jTextField4 = new javax.swing.JTextField();
        jTextField5 = new javax.swing.JTextField();
        jTextField6 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jTextField8 = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        jLabel9.setText("RAZON SOCIAL :");

        jLabel10.setText("EMPRESA :");

        jLabel11.setText("COMPROBANTE :");

        jLabel12.setText("MONTO :");

        jLabel13.setText("OBSERVACIONES :");

        jTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField10ActionPerformed(evt);
            }
        });

        jTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField12ActionPerformed(evt);
            }
        });

        jTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField13ActionPerformed(evt);
            }
        });

        jButton6.setText("GUARDAR ITEM");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 156, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField10))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField11))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField12))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(jLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField13)))
                .addGap(89, 89, 89)
                .addComponent(jButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(345, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(jTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        setClosable(true);
        setMaximizable(true);
        setResizable(true);
        setTitle("Visor de Hoja de Ruta");

        jButton1.setText("<<< Anterior");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Guardar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Siguiente >>>");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Agregar Items");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Anular Hdr");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton7.setText("Reimprimir");
        jButton7.setEnabled(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                    .addComponent(jButton4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 146, Short.MAX_VALUE)
                    .addComponent(jButton7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton3, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton7)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 17, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3))
                .addContainerGap())
        );

        jTable1.setModel(crg);
        crg.addColumn("RAZON SOCIAL");
        crg.addColumn("COMPROBANTE");
        crg.addColumn("SALDO");
        crg.addColumn("CONTACTADO");
        crg.addColumn("ENTREGADO");
        crg.addColumn("MOTIVO FALTA DE ENTREGA");
        //crg.addColumn("REENVIAR");
        Object[] fila=new Object[6];
        Iterator idh=detalleHdr.listIterator();
        while(idh.hasNext()){
            detalle=(DetalleHdr)idh.next();
            fila[0]=detalle.getRazonSocial();
            fila[1]=detalle.getNumeroDeComprobante();
            fila[2]=detalle.getSaldo();
            fila[3]=detalle.getContactoTelefonico();
            fila[4]=detalle.getEntregaCompletada();
            fila[5]=detalle.getMotivoFaltaDeEntrega();
            //fila[6]=true;
            crg.addRow(fila);

        }
        this.jPanel4.setVisible(false);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 910, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 211, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane2.setViewportView(jTextArea1);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 421, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane2, 0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(203, 203, 203))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("HOJA DE RUTA Nª");

        jLabel2.setText("KM INICIALES :");

        jLabel3.setText("KM FINALES :");

        jLabel4.setText("HORA SALIDA :");

        jLabel5.setText("HORA REGRESO :");

        jLabel6.setText("VEHICULO :");

        jLabel7.setText("TOTAL KG :");

        jLabel8.setText("OPERADOR :");

        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("jLabel14");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 116, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField7)
                            .addComponent(jTextField2)
                            .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 161, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField5)
                                    .addComponent(jTextField3, javax.swing.GroupLayout.DEFAULT_SIZE, 27, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField6)
                                    .addComponent(jTextField4, javax.swing.GroupLayout.DEFAULT_SIZE, 35, Short.MAX_VALUE)))
                            .addComponent(jTextField8, javax.swing.GroupLayout.DEFAULT_SIZE, 209, Short.MAX_VALUE)))
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, 624, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 167, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                            .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(126, 126, 126)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(71, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        limpiarCampos();
        cantidad--;
        cargarEncabezadoAnterior();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        limpiarCampos();
        cantidad++;
        cargarEncabezadoSiguiente();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        hdr=(EncabezadoHdr)encabezados.get(cantidad);
        Integer kmInicio=Integer.parseInt(jTextField1.getText());
        Integer kmFin=Integer.parseInt(jTextField2.getText());
        Integer hrIni=Integer.parseInt(jTextField3.getText());
        Integer minIni=Integer.parseInt(jTextField4.getText());
        Integer hrFin=Integer.parseInt(jTextField5.getText());
        Integer minFin=Integer.parseInt(jTextField6.getText());
        if(hdr.getPesoEntregado()==null){
            hdr.setPesoEntregado(0.00);
        }
        hdr.setKmIniciales(kmInicio);
        hdr.setKmFinales(kmFin);
        String horaIn=hrIni+":"+minIni;
        String horaFin=hrFin+":"+minFin;
        hdr.setHoraSalida(hrIni);
        hdr.setMinutosSalida(minIni);
        hdr.setHoraLlegada(hrFin);
        hdr.setMinutosLlegada(minFin);
        DetalleHdr de=new DetalleHdr();
        Boolean entregado=true;
        String motivo=null;
        for(int i=0;i<jTable1.getRowCount();i++){
            entregado=true;
            de=(DetalleHdr)detalleHdr.get(i);
            String comprobante=(String) jTable1.getValueAt(i,1);
            de.setNumeroDeComprobante(comprobante);
            entregado=(Boolean) jTable1.getValueAt(i,4);
            
            de.setEntregaCompletada(entregado);
            motivo=(String) jTable1.getValueAt(i,5);
            de.setMotivoFaltaDeEntrega(motivo);
            //int ree=1;
            //Boolean rre=(Boolean) jTable1.getValueAt(i,6);
            //if(rre){
            //    ree=0;
            //}else{
            if(entregado){
                
            }else{
                System.out.println(" numero de pedidooooooooooo "+de.getNumeroPedidoTango());
                DejarPedidoPendiente(de.getNumeroPedidoTango()); 
            }
            //}
            //de.setReenviarPedido(ree);
        }
        GuardarRecepcionHdr gr=new GuardarRecepcionHdr();
        gr.setEncabed(detalleHdr);
        gr.setEn(hdr);
        gr.start();
        
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        int seleccion=JOptionPane.showConfirmDialog(this, "Confirma la Anulacion?");
        if(JOptionPane.OK_OPTION==seleccion){
        String ax=JOptionPane.showInputDialog("Ingrese el motivo de anulacion :");
        AbmHdr anu=new ModificacionesHdr();
        Integer numero=hdr.getNumero();
        anu.anularHdr(numero,ax);
        limpiarCampos();
        cantidad--;
        cargarEncabezadoAnterior();
        this.dispose();
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField10ActionPerformed

    private void jTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField12ActionPerformed

    private void jTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField13ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        this.jPanel5.setVisible(false);
        this.jPanel4.setVisible(true);
        jTextField9.setText("");
        jTextField10.setText("");
        this.jTextField11.setText("");
        this.jTextField12.setText("");
        this.jTextField13.setText("");
        this.jTextField9.setFocusable(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        String razonSocial=this.jTextField9.getText();
        String empresa=this.jTextField10.getText();
        String comprobante=this.jTextField11.getText();
        String monto=this.jTextField12.getText();
        String observaciones=this.jTextField13.getText();
        DetalleHdr det=new DetalleHdr();
        det.setRazonSocial(razonSocial);
        det.setEmpresa(empresa);
        det.setSaldo(monto);
        det.setObservaciones(observaciones);
        Integer numero=hdr.getNumero();
        System.err.println("NUMERO HDR :"+numero);
        AbmHdr mod=new ModificacionesHdr();
        mod.agregarItem(det,numero, comprobante);
        this.jPanel4.setVisible(false);
        this.jPanel5.setVisible(true);
        limpiarCampos();
        cantidad--;
        cargarEncabezadoAnterior();        
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
    
        /*
        int fila=jTable1.rowAtPoint(evt.getPoint());
              Procesos pr=new Procesos();
              ArrayList motivosF=new ArrayList();
              motivosF=pr.leerMotivosFallidos();
        
        
        Iterator imF=motivosF.listIterator();
        int cantidad=motivosF.size();
        int contador=0;
        Object[] opciones=new Object[cantidad];
        String motivosFF="";
        while(imF.hasNext()){
            
            opciones[contador]=(String)imF.next();
            contador++;
        }
       
        Object seleccion=JOptionPane.showInputDialog(this,"Selecciones Opcion :","Selector de Opciones",JOptionPane.QUESTION_MESSAGE,null,new Object[]{"NO HAY NADIE/NO ATIENDEN","NO SE ENCONTRO DIRECCION","IMPOSIBILIDAD DE LLEGAR A DESTINO","RECHAZA PEDIDO","NO TIENE DINERO","NO ESTA LA PERSONA QUE SE BUSCA","NO TIENE GENTE PARA LA DESCARGA","FUERA DEL HORARIO CONVENIDO","OTROS"}, "NO HAY NADIE/NO ATIENDEN");
        System.out.println("eligio "+seleccion );
        String sel=(String)seleccion;
        String observacionFinal="";
        int ssel=0;
        ssel = pr.leerNumeroMotivoElegido(sel);
        System.err.println("numero elegido "+ssel);
        //switch (ssel){
            //case 1:
        if(sel==null){
            
        }else{
                String observacion=JOptionPane.showInputDialog("Agrega alguna observacion ??");
                observacionFinal=sel+" "+observacion;
                //break;
                
                
        //}
        System.err.println("OBSERVACION FINAL "+observacionFinal);
        jTable1.setValueAt(observacionFinal, fila,5);
        }
        */
    }//GEN-LAST:event_jTable1MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField10;
    private javax.swing.JTextField jTextField11;
    private javax.swing.JTextField jTextField12;
    private javax.swing.JTextField jTextField13;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField3;
    private javax.swing.JTextField jTextField4;
    private javax.swing.JTextField jTextField5;
    private javax.swing.JTextField jTextField6;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField jTextField9;
    // End of variables declaration//GEN-END:variables

    private void cargarHdr() throws SQLException {
        AbmHdr pr=new EncabezadoHdr();
        DecimalFormat fr=new DecimalFormat("00");
        DecimalFormat fPes=new DecimalFormat("####.##");
        encabezados=pr.cargarUltimaHdr();
        cantidad=encabezados.size();
        cantidad--;
        limiteSuperior=cantidad;
        hdr=(EncabezadoHdr)encabezados.get(cantidad);
        String estado="";
        String motivoAnulacion="";
        if(hdr.getEstadoHdr()==1){
            estado=" ANULADA";
            motivoAnulacion=hdr.getMotivoAnulacion();
            this.jButton2.setEnabled(false);
            this.jButton4.setEnabled(false);
            this.jButton5.setEnabled(false);
            this.jTextArea1.setVisible(true);
            this.jTextArea1.setText(motivoAnulacion);
        }else{
            this.jButton2.setEnabled(true);
            this.jButton4.setEnabled(true);
            this.jButton5.setEnabled(true);
            this.jTextArea1.setVisible(false);
            
        }
        fechaReparto=hdr.getFechaReparto();
        jLabel1.setText("HDR :"+hdr.getNumero()+estado);
        String impresion=hdr.getFechaImpresion();
        String lbl=impresion.substring(0,10)+" "+impresion.substring(10);
        jLabel14.setText(lbl);
        String kmIni=Integer.toString(hdr.getKmIniciales());
        String kmF=Integer.toString(hdr.getKmFinales());
        System.out.println("hora de salida "+hdr.getHoraSalida());
        String hrI=fr.format(hdr.getHoraSalida());
        
        String minI=fr.format(hdr.getMinutosSalida());
        String hrF=fr.format(hdr.getHoraLlegada());
        String minF=fr.format(hdr.getMinutosLlegada());
        
        jTextField1.setText(kmIni);
        jTextField2.setText(kmF);
        jTextField3.setText(hrI);
        jTextField4.setText(minI);
        jTextField5.setText(hrF);
        jTextField6.setText(minF);
        jTextField7.setText(hdr.getDescripcionVehiculo());
        jTextField8.setText(hdr.getNombreOperador());
        Double peso=0.00;
        peso=hdr.getPesoEntregado();
        if((peso==null)||(peso==0.00)){
            peso=hdr.getPesoListado();
        }
        String pso=fPes.format(peso);
        jLabel7.setText("TOTAL KG :"+pso);
        visibilidadDeBotones();
        cargarTabla(hdr.getNumero());
    }
    private void cargarEncabezadoAnterior(){
        detalleHdr.clear();
        visibilidadDeBotones();
        hdr=(EncabezadoHdr)encabezados.get(cantidad);
        DecimalFormat fr=new DecimalFormat("00");
        DecimalFormat fPes=new DecimalFormat("####.##");
       //jLabel1.setText("HDR :"+hdr.getNumero());
                String estado="";
        String motivoAnulacion="";
        if(hdr.getEstadoHdr()==1){
            estado=" ANULADA";
            motivoAnulacion=hdr.getMotivoAnulacion();
            this.jButton2.setEnabled(false);
            this.jButton4.setEnabled(false);
            this.jButton5.setEnabled(false);
            this.jTextArea1.setVisible(true);
            this.jTextArea1.setText(motivoAnulacion);
        }else{
            this.jButton2.setEnabled(true);
            this.jButton4.setEnabled(true);
            this.jButton5.setEnabled(true);
            this.jTextArea1.setVisible(false);
            
        }
        fechaReparto=hdr.getFechaReparto();
        jLabel1.setText("HDR :"+hdr.getNumero()+estado);
        String impresion=hdr.getFechaImpresion();
        String lbl=impresion.substring(0,10)+" "+impresion.substring(10);
        jLabel14.setText(lbl);
        String kmIni=Integer.toString(hdr.getKmIniciales());
        String kmF=Integer.toString(hdr.getKmFinales());
        System.out.println("hora de salida "+hdr.getHoraSalida());
        String hrI=fr.format(hdr.getHoraSalida());
        
        String minI=fr.format(hdr.getMinutosSalida());
        String hrF=fr.format(hdr.getHoraLlegada());
        String minF=fr.format(hdr.getMinutosLlegada());
        
        jTextField1.setText(kmIni);
        jTextField2.setText(kmF);
        jTextField3.setText(hrI);
        jTextField4.setText(minI);
        jTextField5.setText(hrF);
        jTextField6.setText(minF);
        jTextField7.setText(hdr.getDescripcionVehiculo());
        jTextField8.setText(hdr.getNombreOperador());
        Double peso=0.00;
        peso=hdr.getPesoEntregado();
        if((peso==null)||(peso==0.00)){
            peso=hdr.getPesoListado();
        }
        String pso=fPes.format(peso);
        jLabel7.setText("TOTAL KG :"+pso);
        cargarTabla(hdr.getNumero());
    }
    private void cargarEncabezadoSiguiente(){
       detalleHdr.clear();
        visibilidadDeBotones();
       hdr=(EncabezadoHdr)encabezados.get(cantidad);
       DecimalFormat fr=new DecimalFormat("00");
       DecimalFormat fPes=new DecimalFormat("####.##");
       //jLabel1.setText("HDR :"+hdr.getNumero());
               String estado="";
        String motivoAnulacion="";
        if(hdr.getEstadoHdr()==1){
            estado=" ANULADA";
            motivoAnulacion=hdr.getMotivoAnulacion();
            this.jButton2.setEnabled(false);
            this.jButton4.setEnabled(false);
            this.jButton5.setEnabled(false);
            this.jTextArea1.setVisible(true);
            this.jTextArea1.setText(motivoAnulacion);
        }else{
            this.jButton2.setEnabled(true);
            this.jButton4.setEnabled(true);
            this.jButton5.setEnabled(true);
            this.jTextArea1.setVisible(false);
            
        }
        fechaReparto=hdr.getFechaReparto();
       jLabel1.setText("HDR :"+hdr.getNumero()+estado);
        String impresion=hdr.getFechaImpresion();
        String lbl=impresion.substring(0,10)+" "+impresion.substring(10);
        jLabel14.setText(lbl);
        String kmIni=Integer.toString(hdr.getKmIniciales());
        String kmF=Integer.toString(hdr.getKmFinales());
        System.out.println("hora de salida "+hdr.getHoraSalida());
        String hrI=fr.format(hdr.getHoraSalida());
        
        String minI=fr.format(hdr.getMinutosSalida());
        String hrF=fr.format(hdr.getHoraLlegada());
        String minF=fr.format(hdr.getMinutosLlegada());
        
        jTextField1.setText(kmIni);
        jTextField2.setText(kmF);
        jTextField3.setText(hrI);
        jTextField4.setText(minI);
        jTextField5.setText(hrF);
        jTextField6.setText(minF);
        jTextField7.setText(hdr.getDescripcionVehiculo());
        jTextField8.setText(hdr.getNombreOperador());
        Double peso=0.00;
        peso=hdr.getPesoEntregado();
        if((peso==null)||(peso==0.00)){
            peso=hdr.getPesoListado();
        }
        String pso=fPes.format(peso);
        jLabel7.setText("TOTAL KG :"+pso);
        cargarTabla(hdr.getNumero());
    }
    private void limpiarCampos(){
        jTextField1.setText("");
        jTextField2.setText("");
        jTextField3.setText("");
        jTextField4.setText("");
        jTextField5.setText("");
        jTextField6.setText("");
        jTextField7.setText("");
        jTextField8.setText("");
        
    }
    private void visibilidadDeBotones(){
        if(cantidad==limiteSuperior){
            jButton3.setVisible(false);
        }else{
            jButton3.setVisible(true);
        }
        if(cantidad==1){
            jButton1.setVisible(false);
        }else{
            jButton1.setVisible(true);
        }
    }
    private void cargarTabla(Integer numero){
        MiModeloTablaCargaHdr crg=new MiModeloTablaCargaHdr();
        jTable1.removeAll();
        AbmHdr pr=new DetalleHdr();
        DetalleHdr detalle=new DetalleHdr();
        Boolean ent=true;
        System.out.println(" hdr "+cantidad);
        try{
            detalleHdr=pr.cargarItemsHdr(numero);
        }catch(Exception ex){
            System.err.println(" NO SE CARGO EL DETALLE DE HDR "+ex);
        } 
             jTable1.setModel(crg);
        crg.addColumn("RAZON SOCIAL");
        crg.addColumn("COMPROBANTE");
        crg.addColumn("SALDO");
        crg.addColumn("CONTACTADO");
        crg.addColumn("ENTREGADO");
        crg.addColumn("MOTIVO FALTA DE ENTREGA");
        //crg.addColumn("REENVIAR");
        Object[] fila=new Object[6];
        Iterator idh=detalleHdr.listIterator();
        while(idh.hasNext()){
            detalle=(DetalleHdr)idh.next();
            fila[0]=detalle.getRazonSocial();
            fila[1]=detalle.getNumeroDeComprobante();
            fila[2]=detalle.getSaldo();
            fila[3]=detalle.getContactoTelefonico();
            fila[4]=detalle.getEntregaCompletada();
            String motivo=" ";
            System.out.println(detalle.getMotivoFaltaDeEntrega());
            if("null".equals(detalle.getMotivoFaltaDeEntrega())){
            motivo=" ";
            }else{
            motivo=detalle.getMotivoFaltaDeEntrega();
            }
            fila[5]=motivo;
                        if(detalle.getReenviarPedido()==0){
                //fila[6]=true;
            }else{
            //fila[6]=false;
            }
            crg.addRow(fila);

        }
    }
    private void DejarPedidoPendiente(String numeroPedido){
        /*
        Procesos pro=new PedidosParaReparto();
        ArrayList listadoPed=new ArrayList();
        ArrayList corregido=new ArrayList();
        PedidosParaReparto pedid=new PedidosParaReparto();
        listadoPed=pro.detallePedidosParaCorreccion(numeroPedido, fechaReparto);
        Iterator iLis=listadoPed.listIterator();
        while(iLis.hasNext()){
            pedid=(PedidosParaReparto)iLis.next();
            PedidosParaReparto pedidos=new PedidosParaReparto();
            System.out.println("DETALLE EMPRESA "+pedid.getEmpresa());
            pedidos=(PedidosParaReparto) pro.regenerarCantidades(pedid);
            Double cantOr=(Double)pedidos.getCantidadArticulo();
            pedidos.setCantidadArticuloPendiente(cantOr);
            System.out.println(" PEDIDO "+pedidos.getCodigoTangoDePedido());
            corregido.add(pedidos);
        }
        pro.guardarDetallePedido(corregido);
*/
    }
}
